name: $(date:yyyy.M.d)-$(Build.SourceBranchName)-$(date:HHmm)

trigger:
  branches:
    include:
    - '*'

stages:
  - template: stages/build.yaml

  - template: stages/deploy.yaml
    parameters:
      connectedServiceName: dev1
      subscriptionId: YOUR-SUBSCRIPTION-ID
      environment: development
      location: west europe, north europe
      dependsOn: build
      condition: succeeded()

  - template: stages/deploy.yaml
    parameters:
      connectedServiceName: prd1 
      subscriptionId: YOUR-SUBSCRIPTION-ID
      environment: production
      location: west europe, north europe
      dependsOn: deploy_development
      condition: >
        and (
          succeeded(),
          or(
            eq(variables['Build.SourceBranch'], 'refs/heads/master'),
            eq(variables['Build.SourceBranch'], 'refs/heads/main')
          )
        )